### ISSUE TITLE
cannot import name 'total_variation' from 'kornia'

### ISSUE THREAD

**Issue by Ayxm1412** [rozumden/ShapeFromBlur#1]
hi!

what an interesting work!

I have some trouble running the test demo.  I have downloaded the newest kornia from pip and tried this https://github.com/kornia/kornia/discussions/1290, but still, get the problem. I wonder if you could give your environment requirements to run the test.

thx :)

``` shell
Traceback (most recent call last):
  File "optimize.py", line 7, in <module>
    from shapefromblur import *
  File "/dev-data/xxx/projects/SfB/ShapeFromBlur-main/shapefromblur.py", line 12, in <module>
    from models.loss import *
  File "/dev-data/xxx/projects/SfB/ShapeFromBlur-main/models/loss.py", line 3, in <module>
    from kornia import total_variation
ImportError: cannot import name 'total_variation' from 'kornia'
```

**Comment by rozumden** [comment]
Hi, thanks!

I've created a "requirements.txt" file. We support kornia versions >0.5.10. Please let me know if this works for you.

Best regards,
Denys

**Comment by Ayxm1412** [comment]
> Hi, thanks!
> 
> I've created a "requirements.txt" file. We support kornia versions >0.5.10. Please let me know if this works for you.
> 
> Best regards, Denys

thanks!
I've installed the kornia==0.5.10 and kaolin==0.9.0. It solved my problem. Thank you again for answering such a simple question。
Wish you have a nice day!
